### ISSUE TITLE
Support for C4D R23?

### ISSUE THREAD

**Issue by msanity** [gr4ph0s/c4d_redshift_light_lister#2]
Hi. Love the plugin, but it doesn't work in R23. Do you have any plans to update so it's compatible?

**Comment by gr4ph0s** [comment]
I don't have an immediate plan to update it, however, I may consider to do it. At least the bare minimum update, just updating to Python3

**Comment by msanity** [comment]
If you did the bare minimum to get it running on Python 3, that would be awesome!

**Comment by gr4ph0s** [comment]
Here you are https://github.com/gr4ph0s/c4d_redshift_light_lister/releases/tag/R23 :)

**Comment by msanity** [comment]
Seems to be working great - thank you!
